blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', views.portfolio_records_views, name='homepage'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    date = models.DateField()

    def __str__ (self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

portfolio/forms.py
from django import forms
from portfolio.models import Project

class portfolio_records_form(forms.Modelform):
    class Meta():
        model = Project
        fields = '__all__'

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Blog
# Create your views here.
def all_blogs(request):
    blogs = Blog.objects.order_by('-date')[:5]
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})

portfolio/views.py
from django.shortcuts import render
from portfolio.models import Project
# Create your views here.
def portfolio_records_views(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {'projects': projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>
<br>
<br>
<h3 class="text-center mb-5">Tahseen has written {{blogs.count}} blog{{blogs.count|pluralize}}</h3>

{% if blogs %}
  {% for item in blogs %}
    <div class="row justify-content-center my-3">
      <div class="col-md-10">
        <h2>{{ item.title }}</h2>
        <h5 class="text-muted">{{ item.date|date:'j M Y' }}</h5>
        <p>{{ item.description }}</p>
      </div>
    </div>
  {% endfor %}
{% else %}
  <p>No blogs found</p>
{% endif %}
</body>
</html>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <title></title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% static 'portfolio/mybio.pdf' %}">Tahseen Uzumaki</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Other
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="https://www.facebook.com/tahseen.uzumaki/">Facebook</a></li>
            <li><a class="dropdown-item" href="https://www.instagram.com/tahseenzz/">Instagram</a></li>
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

    {% block content %}{% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>PORTFOLIO</title>
</head>
<body>
<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/pic.jpg' %}" class="img-fluid">
  </div>
</div>
<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
      <h1 id="hometext" class="font-weight-bold">Tahseen is an expert Django Web Devloper</h1>
  </div>
</div>
<h2 class="mt-5"><b>Portfolio</b></h2>
<hr>
<div class="row">
  {% for item in projects %}
    <div class="col-lg-4 col-md-6">
      {% if item.url %}
      <a href="{{ item.url }}">
      <img src="{{ item.image.url }}" class="image">
      </a>
      {% else %}

      <img src="{{ item.image.url }}" class="image">
      {% endif %}
      <h3><b>{{ item.title }}</b></h3>
      <p>{{ item.description }}</p>
    </div>
  {% endfor %}

</div>
</body>
</html>
{% endblock %}